FROM nginx:1.21.0-alpine
RUN apk add nano && apk add curl
COPY ./index.html /usr/share/nginx/html
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d
COPY ./.htpasswd /etc/nginx/.htpasswd
EXPOSE 80
