FROM nginx:1.21.0-alpine
RUN apk add nano && apk add curl
COPY ./index.html /usr/share/nginx/html
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d
COPY ./.htpasswd /etc/nginx/.htpasswd
COPY ./cert.pem /etc/ssl/certs/cert.pem
COPY ./key.pem /etc/ssl/private/key.pem
COPY ./cloudflare.crt /etc/ssl/cloudflare.crt
EXPOSE 443
