apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
       app: backend
    spec:
      containers:
      - name: backend-container
        image: public.ecr.aws/z2b5z3a0/hewson-backend:latest 
        ports:
        - containerPort: 3000
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: root-username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: root-password
