apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database-service
spec:
  type: LoadBalancer
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
