apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8scluster
  region: ap-southeast-2

nodeGroups:
   - name: node1
     desiredCapacity: 1
     instanceType: t3.small
     ssh:
        publicKeyName: hewson-k8s
   - name: node2
     desiredCapacity: 1
     instanceType: t3.small
     ssh:
        publicKeyName: hewson-k8s
   - name: node3
     desiredCapacity: 1
     instanceType: t3.small
     ssh:
        publicKeyName: hewson-k8s
