apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sca.hewson.io 
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
